pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            environment {
                // Define the path to the Node.js binary based on your Jenkins configuration
                NODEJS_HOME = tool name: 'NodeJS-14.17.3', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
                PATH = "${NODEJS_HOME}/bin:${PATH}"
            }
            steps {
                script {
                    // Run npm install
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    // Your build steps, for example: npm run build
                    sh 'npm run build'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Your test steps, for example: npm test
                    sh 'npm test'
                }
            }
        }

        stage('Deploy') {
            steps {
                // Your deployment steps
                // This section is a placeholder; customize it based on your deployment strategy
            }
        }
    }
}
