pipeline {
    agent any

    tools {
        // Replace "Your_NodeJS_Installation_Name" with the actual Node.js installation name
        nodejs "NodeJS-14.17.3"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    // Run npm install
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    // Your build steps, for example: npm run build
                    sh 'npm run build'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Your test steps, for example: npm test
                    sh 'npm test'
                }
            }
        }

        stage('Deploy') {
            steps {
                // Your deployment steps
                // This section is a placeholder; customize it based on your deployment strategy
            }
        }
    }
}
